# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0489e40f7a34e1eb2465f2815f9d4eb8"
name = "digitalocean-test"
handle = "digitalocean-test"
application_url = "https://intended-winds-friendly-conscious.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-extension-test-sj.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://intended-winds-friendly-conscious.trycloudflare.com/auth/callback",
  "https://intended-winds-friendly-conscious.trycloudflare.com/auth/shopify/callback",
  "https://intended-winds-friendly-conscious.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
